[buildPlans.iosevka-custom]            # <iosevka-custom> is your plan name
family = "XD"                          # Font menu family name
design = [
    "common styles",
    'v-y-curly',
    'v-g-singlestorey',
    'v-a-singlestorey',
    'v-brace-straight'
]
upright = [
    "upright-only",
    "styles",
    'v-y-curly',
    'v-g-singlestorey',
    'v-a-singlestorey',
    'v-brace-straight'
]
italic = ["italic-only", "styles"]     # Italic-only styles
oblique = ["oblique-only", "styles"]   # Oblique-only styles

# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
# [weights.thin]
# shape = 100
# menu  = 100
# css   = 100

[weights.extralight]
shape = 200
menu  = 200
css   = 200

[weights.light]
shape = 300
menu  = 300
css   = 300

[weights.regular]
shape = 400
menu  = 400
css   = 400

[weights.medium]
shape = 500
menu  = 500
css   = 500

[weights.semibold]
shape = 600
menu  = 600
css   = 600

# [weights.bold]
# shape = 700
# menu  = 700
# css   = 700

[weights.extrabold]
shape = 800
menu  = 800
css   = 800

[weights.heavy]
shape = 900
menu  = 900
css   = 900

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-custom.slants]
upright = "normal"
italic = "italic"
oblique = "oblique"