[buildPlans.iosevka-custom]            # <iosevka-custom> is your plan name
family = "XD"                          # Font menu family name
design = [
    "common styles",
    'v-y-curly',
    'v-g-singlestorey',
    'v-a-singlestorey',
    'v-brace-straight'
]
upright = [
    "upright-only",
    "styles",
    'v-y-curly',
    'v-g-singlestorey',
    'v-a-singlestorey',
    'v-brace-straight'
]
italic = ["italic-only", "styles"]     # Italic-only styles
oblique = ["oblique-only", "styles"]   # Oblique-only styles

# Override default building weights
# When buildPlans.<plan name>.weights is absent
# All weights would built and mapped to default shape/CSS
[buildPlans.iosevka-custom.weights.regular]
shape = 200                            # Weight for glyph shapes
menu  = 200                            # Weight for menu name
css   = 200                            # Weight for WebFont CSS

[buildPlans.iosevka-custom.weights.bold]
shape = 400
menu  = 400
css   = 400

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[buildPlans.iosevka-custom.slants]
upright = "normal"
italic = "italic"
oblique = "oblique"