#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files
#   can be useful for fixing corrupted setups

#!/usr/bin/env bash

# summary
#   this just removes all of the can-be deleted files like cache's
#   devs should never have to worry about running the cleaning file
#   
#   this can be useful for fixing corrupted setups

unlink "$PROJECTR_FOLDER/home/.cache/nix"

# the usual things
rm -rfv "$PROJECTR_FOLDER/.cache" "$PROJECTR_FOLDER/"**/*.cleanable "$PROJECTR_FOLDER/"**/*.cleanable.*
mkdir -p "$PROJECTR_FOLDER/.cache" && touch "$PROJECTR_FOLDER/.cache/.keep" # restore the keep file

# python cache at any level (half second to rebuild these)
rm -rf "$PROJECTR_FOLDER/"**/__pycache__
